### ISSUE TITLE
location -> coords causes issue.

### ISSUE THREAD

**Issue by Kestanous** [zeroasterisk/meteor-cordova-geolocation-background#2]
I am not sure if one of your packages updated or if adding mdg:geolocation caused this (removing mdg:geolocation does not fix) but my GeoLocations are coming in as coords not locations:
```
[omitted]: send: error - location is invalid
[omitted]: {"timestamp":1421595368988,"coords":{"speed":null, "heading":null, "altitudeAccuracy":null, "accuracy":1572, "altitude":null, "longitude":-79.0030039,"latitude":35.9205203}}
```
Could you check for both? Or do you know what caused this switch?

**Comment by Kestanous** [comment]
I coped your code directly into my app to test this and got this far:

```
    if (!_.isObject(location)) {
      console.error('GeolocationBG: send: error - location is invalid');
    } 
    if (!_.has(location, 'longitude')) {
      if (_.has(location, 'coords')) {
        location = location.coords;
      } else {
        console.error('GeolocationBG: send: error - location is invalid');
        return;
      }
    }
```

But now I am getting `Access-Control-Allow-Origin` issues. However it looks like the above fixed the issue.

**Comment by Kestanous** [comment]
I have fixed this for my use case but replacing `HTTP.call` with `Meteor.call`. This is ideal for me because now it users meteor user validation.

**Comment by Kestanous** [comment]
Not resolved, Meteor.call will not work on android.

**Comment by Kestanous** [comment]
Hmm looks like the coors problem not an issue with this package: https://github.com/meteor/meteor/issues/3469. If thats the case my patch should resolve this issue.

**Comment by zeroasterisk** [comment]
can you please submit a PR to at least handle the different `coords` vs. `location` pathing possible?

Also - if `Meteor.call` will work better, it might be worth trying - let me know.

Thanks for the help!! :+1:

**Comment by Kestanous** [comment]
Sorry I forgot to link https://github.com/zeroasterisk/meteor-cordova-geolocation-background/pull/4.

Meteor.call would be the best solution. But on android it fired once and then only went over HTTP. But on that first fire I had all my security working perfectly.

**Comment by Kestanous** [comment]
This issue is resolved so closing. But for other android users I am still waiting on this core meteor issue: https://github.com/meteor/meteor/issues/3469.
