### ISSUE TITLE
Replace HTTP with DDP?

### ISSUE THREAD

**Issue by Kestanous** [zeroasterisk/meteor-cordova-geolocation-background#3]
Did you consider or try using DDP directly in the background? It would be nice to be able to directly upload and authenticate with stock meteor rather then open up HTTP, which could cause problems or be less reliable (throttling and dropping updates) .

**Comment by Kestanous** [comment]
You did this because android constraints... this is a real same...

**Comment by zeroasterisk** [comment]
I agree - it is a shame - the Cordova plugin (which I am not the author of) uses a background service on Android which doesn't use the AJAX function at all.

https://github.com/christocracy/cordova-plugin-background-geolocation#android

**Comment by Kestanous** [comment]
I am not very familiar with the android architecture, do you know if it would be possible to build a plug-in in which we could use meteor.call? If our app scales as I expect we could have thousands of location updates a second, each from a different user (we are doing vehicle tracking). Do you have any thoughts/recommendations for handling this? Do you think the current setup could/should handle that? Security is also a concern so I will likely have to add cookies.

**Comment by zeroasterisk** [comment]
# I don't know anything about how Android works under the hood, so I can't answer that, sorry
# the 1000s of updates a second all comes down to your Meteor app, not this plugin... you can test it now with a lot of curl requests... you may well need to scale horizontally to support that scale, but again, that's not really at all about this plugin
# I use the `zeroasterisk:throttle` package to limit the possible "flooding" of the background update path to 100 requests every second (scale as needed).
# I think if you passed in the Meteor `User._id` and perhaps the device UUID or whatever, it would be easy to also throttle on the unique combination and only allow each device 1 hit every 5 seconds or something...  not perfect, will still tax your server if they flood you, but better than nothing.
# you can also verify that the `User._id` exists, which may be a psuedo-security

IM me via Google+ Hangouts (my github username @gmail.com) - I'd like to talk to you more

**Comment by Kestanous** [comment]
1. Ah, well no worries. We will investigate it should we find the need.

2. (& 3) I figured as much. Thanks for confirming.

4. (& 5) The catch is if someone gets ahold of a user's id and UUID, which would be a trick, then they can mess with their location without any verification. Throttle on userId + UUID would be a good idea though.

**Comment by christocracy** [comment]
Sorry to comment on a closed issue, but I am the author of the cordova plugin.  I have refactored Android and it is much improved.  I've ripped out the HTTP layer in favor of executing the js callback (as ios does), so no more FG service.  More importantly, the battery-efficiency is vastly superior.

http://christocracy.github.io/cordova-background-geolocation/

**Comment by zeroasterisk** [comment]
SWEET!  I'll get this updated very soon.  I very much appreciate the update notice (and the plugin).

**Comment by Kestanous** [comment]
Thanks a bunch!!! We ended up having to do some crazy hacking, we have screen keep alive and geolocation (foreground) in our app. This ended up working, the users should be aware of us tracking them, but it was an ugly fix and bad UI. Not to mention battery life hell. This is greatly appreciated, thanks to you both!

**Comment by christocracy** [comment]
You can thank me by purchasing a license for $500 ;)  in fact that's the
only way to access the new Android plugin.

>$50k of R&D over the past year has gone into my cordova plugin so far.

On Friday, March 6, 2015, Sivli Kestanous <notifications@github.com> wrote:

> Thanks a bunch!!! We ended up having to do some crazy hacking, we have
> screen keep alive and geolocation (foreground) in our app. This ended up
> working, the users should be aware of us tracking them, but it was an ugly
> fix and bad UI. Not to mention battery life hell. This is greatly
> appreciated, thanks to you both!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zeroasterisk/meteor-cordova-geolocation-background/issues/3#issuecomment-77589678>
> .
>


-- 
Snet from Gmail Mobile
