### ISSUE TITLE
Package not found

### ISSUE THREAD

**Issue by jhmacdon** [zeroasterisk/meteor-cordova-geolocation-background#5]
While adding package zeroasterisk:meteor-cordova-geolocation-background:
error: no such package

**Comment by hems** [comment]
+2

same error here //=

**Comment by hems** [comment]
@jhmacdon 
i just did
````meteor search geolocation````
the package appeared on terminal, then i copy & pasted from there and everything worked.

**Comment by zeroasterisk** [comment]
Readme typeo. Will correct. Sorry!

**Comment by hems** [comment]
@zeroasterisk awesome! issue closed :P

**Comment by zeroasterisk** [comment]
meteor add zeroasterisk:cordova-geolocation-background
