### ISSUE TITLE
Timeout expired

### ISSUE THREAD

**Issue by bipin244** [zeroasterisk/meteor-cordova-geolocation-background#9]
Uncaught Error: GeolocationFG error [3] Timeout expired [500]

**Comment by zeroasterisk** [comment]
1. this should be reported on the [FG](https://github.com/zeroasterisk/meteor-cordova-geolocation-foreground) package, not this one *(BG)*
2. any chance you could give me more info?  Requests SHOULD time out, if not returned, and an error should be thrown... [see code](https://github.com/zeroasterisk/meteor-cordova-geolocation-foreground/blob/master/cordova-geolocation.js#L16)  *suggestions?*
